### ISSUE TITLE
"Cuda error: invalid configuration argument" when called run_fusion()

### ISSUE THREAD

**Issue by Yzhbuaa** [Gorilla-Lab-SCUT/gmvs#1]
Hello, the log is shown below. When I run first_mvs.sh on a set of images with resolution 1920 x 1440, I met the cuda error. I do not know the cause of this bug. Could you provide some clue? Thank you! 

![img_v2_410dd534-bb76-4443-b731-0c5d2501cf3g](https://github.com/Gorilla-Lab-SCUT/gmvs/assets/44798666/c9f0a97b-517b-435d-96cd-0b666f21a03a)

**Comment by Huang-ZhangJin** [comment]
We have fixed this issue in the newest commit.
